version: '3.4'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    ports: 
      - 8080:8080
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin